Feat: Creación reporte general por periodo y nivel academico
udistrital/sga_mid_admisiones pull request #12
Opened 2024-04-22 03:49 UTC by Moreraz20

udistrital/sga_dicumentacion#164
# Nuevo reporte

Se crea un nuevo reporte dinámico, que permite listar todos los aspirantes de todos los proyectos definidos para un periodo académico y nivel específicos.

2024-04-25 14:16 UTC, NeFaWaltPint commented on services/swagger.zip
bueno, este no estaba dentro de la lista de .gitignore
pero raro que que demás se haya subido, solo se requiere el swagger.json y swagger.yml

2024-04-25 14:20 UTC, NeFaWaltPint requested changes
Todo excelente con la lógica, pero se cargó archivos innecesarios del swagger, solo dejar dentro de carpeta swagger: el .json y el .yml, lo demás y el zip retirarlo.

2024-05-07 14:19 UTC, fabianbarreto02 approved these changes

2024-05-07 14:42 UTC, fabianbarreto02 approved these changes

2024-05-07 14:43 UTC, merged